from .parse_response import SYSTEM_PROMPT as PARSE_RESPONSE_PROMPT
from .extract_evidence import SYSTEM_PROMPT as EXTRACT_EVIDENCE_PROMPT
from .generate_question import SYSTEM_PROMPT as GENERATE_QUESTION_PROMPT
from .generate_report import SYSTEM_PROMPT as GENERATE_REPORT_PROMPT

__all__ = [
    "PARSE_RESPONSE_PROMPT",
    "EXTRACT_EVIDENCE_PROMPT",
    "GENERATE_QUESTION_PROMPT",
    "GENERATE_REPORT_PROMPT",
]
